---
title: 'FLAcro23: Data import and tidying'
author: "Ross Cunning"
date: "2024-09-26"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r load_libraries}
library(readxl)
library(parzer)
library(tidyverse)
library(geosphere)
```

# Import Acropora mortality data

```{r import_data}
## CRF data
crf0 <- read_xlsx("data/raw/CRF_FL_Acropora_data_.xlsx")

crf <- crf0 %>%
  mutate(
    data_provider = "crf",
    site = paste(Site, Mosaic_Area_Name),
    lat = Latitude,
    lon = Longitude,
    date = as_date(Date),
    species = Spp,
    coral_type = `Wild/Outplant`,
    n_alive = `N (surviving colonies)`,
    n_dead = `N (colonies)` - `N (surviving colonies)`,
    n_geno = `N (Genotypes, if known)`
  ) %>%
  dplyr::select(data_provider, site, lat, lon, date, species, coral_type,
         n_alive, n_dead, n_geno)


## Mote data
mml0 <- read_xlsx("data/raw/FL_Acropora data_MoteMarineLaboratory.xlsx")

mml <- mml0 %>%
  mutate(
    data_provider = "mml",
    site = Site,
    lat = Latitude,
    lon = Longitude,
    date = as_date(Date),
    species = `Spp (APAL/ACER)`,
    coral_type = `Wild/Outplant`,
    n_alive = `N (surviving colonies)`,
    n_dead = `N (colonies)` - `N (surviving colonies)`,
    n_geno = `N (Genotypes, if known)`
  ) %>%
  dplyr::select(data_provider, site, lat, lon, date, species, coral_type,
         n_alive, n_dead, n_geno)


## NSU data
nsu0 <- read_xlsx("data/raw/NSU_Gilliam_Acropora data.xlsx")

nsu <- nsu0 %>%
  mutate(
    data_provider = "nsu",
    site = Site,
    lat = parse_lat(Latitude),
    lon = parse_lon(Longitude) * -1,
    date = as_date(Date),
    species = `Spp (APAL/ACER)`,
    coral_type = `Wild/Outplant`,
    n_alive = `N (surviving colonies)`,
    n_dead = `N (colonies)` - `N (surviving colonies)`,
    n_geno = `N (Genotypes, if known)`
  ) %>%
  dplyr::select(data_provider, site, lat, lon, date, species, coral_type,
         n_alive, n_dead, n_geno)


## UM data
um0 <- read_xlsx("data/raw/UM_AcroporaData.xlsx")

um <- um0 %>%
  mutate(
    data_provider = "um",
    site = Site,
    lat = Latitude,
    lon = Longitude,
    date = as_date(Date),
    species = `Spp (APAL/ACER)`,
    coral_type = `Wild/Outplant`,
    n_alive = `N (surviving colonies)`,
    n_dead = `N (colonies)` - `N (surviving colonies)`,
    n_geno = `N (Genotypes, if known)`
  ) %>%
  dplyr::select(data_provider, site, lat, lon, date, species, coral_type,
         n_alive, n_dead, n_geno)

# BNP data
bnp0 <- read_xlsx("data/raw/FL_Acropora data_NPS-BNP.xlsx", sheet = "NPS BNP data", n_max = 20)
bnp <- bnp0 %>%
  #data cleaning
  mutate(Date=case_when(Date=="Mar24"~ymd("2024/3/1"),
                        Date=="May24"~ymd("2024/05/1")),
         `N (surviving colonies)`=as.numeric(str_extract(`N (surviving colonies)`, "[0-9]+")),
         `N (colonies)`=as.numeric(str_extract(`N (colonies)`, "[0-9]+")),
         `N (Genotypes, if known)`=case_when(str_detect(`N (Genotypes, if known)`, "pend|unk")~NA,
                                                        TRUE~as.numeric(`N (Genotypes, if known)`)),
         `Wild/Outplant`=ifelse(str_detect(`Wild/Outplant`, "outplant"), "Outplant", "Wild"),
         `Spp`=str_to_upper(`Spp`)) %>%
  mutate(
    data_provider = "bnp",
    site = Site,
    lat = Latitude,
    lon = Longitude,
    date = as_date(Date),
    species = `Spp`,
    coral_type = `Wild/Outplant`,
    n_alive = `N (surviving colonies)`,
    n_dead = `N (colonies)` - `N (surviving colonies)`,
    n_geno = `N (Genotypes, if known)`
  ) %>%
  
  dplyr::select(data_provider, site, lat, lon, date, species, coral_type,
         n_alive, n_dead, n_geno)

## FWC data
fwc0 <- read_xlsx("data/raw/FL_APAL_Summary Data.xlsx", sheet = "FWC", 
                  n_max = 28,
                  na = c("N/A", "n/a")) %>%
  filter(Site != "REGION SUMMARY")

fwc <- fwc0 %>%
  mutate(
    data_provider = "fwc",
    site = Site,
    lat = Latitude,
    lon = Longitude,
    date = as_date(Date),
    species = `Spp`,
    coral_type = `Wild/Outplant`,
    n_alive = `N (surviving colonies)`,
    n_dead = `N (colonies)` - `N (surviving colonies)`,
    n_geno = `N (Genotypes, if known)`
  ) %>%
  dplyr::select(data_provider, site, lat, lon, date, species, coral_type,
         n_alive, n_dead, n_geno)


## USGS data
usgs0 <- read_xlsx("data/raw/FL_APAL_Summary Data.xlsx", sheet = "KUFFNER", 
                  n_max = 12,
                  na = c("N/A", "n/a")) %>%
  filter(Site != "REGION SUMMARY")

usgs <- usgs0 %>%
  mutate(
    data_provider = "usgs",
    site = Site,
    lat = Latitude,
    lon = Longitude,
    date = as_date(Date),
    species = `Spp`,
    coral_type = `Wild/Outplant`,
    n_alive = `N (surviving colonies)`,
    n_dead = `N (colonies)` - `N (surviving colonies)`,
    n_geno = `N (Genotypes, if known)`
  ) %>%
  dplyr::select(data_provider, site, lat, lon, date, species, coral_type,
         n_alive, n_dead, n_geno)


## DW data
dw0 <- read_xlsx("data/raw/FL_APAL_Summary Data_DEW2.xlsx", sheet = "DANA W", 
                  n_max = 95,
                  na = c("N/A", "n/a")) %>%
  filter(Site != "REGION SUMMARY")

dw <- dw0 %>%
  mutate(
    data_provider = "dw",
    site = Site,
    lat = Latitude,
    lon = Longitude,
    date = as_date(Date),
    species = `Spp`,
    coral_type = `Wild/Outplant`,
    n_alive = `N (surviving colonies)`,
    n_dead = `N (colonies)` - `N (surviving colonies)`,
    n_geno = `N (Genotypes, if known)`
  ) %>%
  dplyr::select(data_provider, site, lat, lon, date, species, coral_type,
         n_alive, n_dead, n_geno)

# Dana counted fission/partial mortality resulting in separate ramets, so number of survivors is sometimes higher than original total number of colonies. In these cases, set number of survivors to equal the number of original colonies.
dw <- dw %>%
  mutate(n_dead = pmax(0, n_dead))

dw <- dw %>%
  group_by(data_provider, site, date, species, coral_type) %>%
  summarize(n_alive = sum(n_alive),
            n_dead = sum(n_dead),
            lat = mean(lat),
            lon = mean(lon))

# Shedd DRTO ACER data
# June outplants
jun <- expand_grid(date = as.Date("2023-06-30"),
                   site = c("Pulaski Shoal", "Texas Rock", "Southwest Channel"),
                   n_dead = 0,
                   n_alive = 180,
                   coral_type = "Outplant",
                   data_provider = "shedd",
                   species = "ACER")

dtac <- read_csv("data/raw/fouling_metadata.csv")

dtac <- dtac %>%
  filter(!is.na(Ranking)) %>%
  group_by(Site, Lat, Lon) %>%
  summarize(n_dead = sum(Ranking > 1),
            n_alive = sum(Ranking == 1)) %>%
  mutate(date = as.Date("2023-09-09"),
         data_provider = "shedd",
         species = "ACER",
         coral_type = "Outplant",
         n_geno = NA) %>%
  ungroup() %>%
  dplyr::select(data_provider, site = Site, lat = Lat, lon = Lon,
                date, species, coral_type, n_alive, n_dead, n_geno)
  
dtac <- dtac %>%
  bind_rows(jun) %>%
  group_by(site) %>%
  mutate(lat = ifelse(is.na(lat), first(na.omit(lat)), lat),
         lon = ifelse(is.na(lon), first(na.omit(lon)), lon)) %>%
  ungroup()


## MIR data
mir0 <- read_xlsx("data/raw/MIR_Acropora data.xlsx")

mir <- mir0 %>%
  mutate(
    data_provider = "mir",
    site = Site,
    lat = Latitude,
    lon = Longitude,
    date = as_date(Date),
    species = `Spp (APAL/ACER)`,
    coral_type = `Wild/Outplant`,
    n_alive = `N (surviving colonies)`,
    n_dead = `N (colonies)` - `N (surviving colonies)`,
    n_geno = `N (Genotypes, if known)`
  ) %>%
  dplyr::select(data_provider, site, lat, lon, date, species, coral_type,
         n_alive, n_dead, n_geno)


# Combine all data
df0 <- bind_rows(
  crf, dw, fwc, mml, nsu, um, usgs, dtac, mir, bnp
) %>%
  mutate(n_total = n_dead + n_alive,
         pct_mort = n_dead / n_total)
```

# Tidy and filter data
```{r tidy_filter}
# Change coral_type WILD to Wild
df0 <- df0 %>%
  mutate(coral_type = case_when(coral_type == "WILD" ~ "Wild", TRUE ~ coral_type))

# Create a categorical variable for number of ramets surveyed at each site
df0 <- df0 %>%
  mutate(n_total_cat = cut(n_total, breaks = c(0, 10, 100, 1000, 7000), right = FALSE))

# Filter to just June 2023 and after
df0 <- df0 %>% filter(date > "2023-06-01")
```

# Cluster sites and assign subregions
```{r tidy_data}
# Ensure unique site names (some diff. groups used same site name (e.g., "100") for diff. sites)
df1 <- df0 %>%
  mutate(site = paste(data_provider, site, sep = "."))

# -----------
# Assign Subregions based on DRM subregions
subregions <- read_csv("data/raw/DRM_sites_2023.csv")

# Calculate distances between acropora data locations and drm sites (with subregion info)
df1 <- df1 %>% drop_na(lat, lon)   # Omit acropora data sites with missing coords
dist_matrix <- distm(df1[, c("lat", "lon")], subregions[, c("lat", "lon")], fun = distHaversine)

# Find the nearest DRM site (with subregion) for each entry in acropora data
nearest_indices <- apply(dist_matrix, 1, which.min)

# Add nearest subregion to df
df1 <- df1 %>%
  mutate(subregion = subregions$subregion[nearest_indices]) %>%
  drop_na(date) %>%
  droplevels()

# Change Mid-Upper Keys Transition to Middle Keys 
# Combine Mid-Upper Keys Transition with Middle Keys (only ~2 timepoints)
df1 <- df1 %>%
  mutate(subregion = case_when(subregion == "Mid-Upper Keys Transition" ~ "Middle Keys",
                               TRUE ~ subregion)) %>%
  mutate(subregion = factor(subregion, levels = c("Broward-Miami", "Biscayne", "Upper Keys",
                                                  "Middle Keys", "Lower Keys", "Tortugas--Dry Tortugas NP")))

# -----------
# Cluster sites that are close together
dist_mat <- distm(df1[, c("lon", "lat")], fun = distHaversine)
hc <- hclust(as.dist(dist_mat), method = "complete")
clusters <- cutree(hc, h = 2000)  # Cluster based on 2000m threshold
df1$siteclust <- as.character(clusters)

# ggplot(df, aes(x = lon, y = lat, color = as.factor(siteclust))) +
#   geom_point()

# Combine all data by site cluster/date
df <- df1 %>%
  group_by(siteclust) %>%
  mutate(lat = mean(lat),
         lon = mean(lon)) %>%
  group_by(siteclust, subregion, date, species, coral_type, lat, lon) %>%
  summarize(n_alive = sum(n_alive),
            n_dead = sum(n_dead)) %>%
  ungroup() %>%
  mutate(n_total = n_dead + n_alive,
         pct_mort = n_dead / n_total)
```

# Add DHW data for all site clusters
```{r add_DHW}
# Import all NetCDF files for each date from June 1 through December 31, 2023
nc.files <- list.files("data/raw/DHW_2023", pattern = "*.nc$", full.names = TRUE)

# List of sites that we want to get DHW values for
sites <- df %>%
  dplyr::distinct(siteclust, subregion, lon, lat)

# Open all DHW NCDF4 files
library(ncdf4) # package for netcdf manipulation
library(raster) # package for raster manipulation
nc.data <- tibble(file = nc.files) %>%
  mutate(date = map_chr(file, ~str_extract(., "2023\\d+"), format = "%Y%m%d"),
         data = map(file, nc_open),
      dhw.all = map(data, ~ncvar_get(., "degree_heating_week", start = c(1930, 1240, 1), count = c(91, 81, 1))),
            r = map(dhw.all, ~raster(t(.), xmn = -83.525, xmx = -78.975, ymn = 23.975, ymx = 28.025,
                                     crs = CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs+ towgs84=0,0,0"))),
       coords = list(sites),
          dhw = map2(r, coords, ~raster::extract(.x, SpatialPoints(.y[,3:4]), method = "simple")))

out <- nc.data %>% dplyr::select(date, coords, dhw) %>% unnest() %>%
  mutate(date = as_date(date, format = "%Y%m%d"))

# Check that all sites got DHW values
dhws <- out %>%
  group_by(siteclust) %>%
  dplyr::summarize(avgdhw = mean(dhw))
nodhw <- dhws %>% filter(is.na(avgdhw))
#nodhw
## 6 siteclusts did not get DHW -- outside of 5km pixels (too close to land)

# Assign missing dhws value of closest site that has a dhw value
library(FastKNN)

# matrix of neighbours
n <- nrow(sites)
k <- 35 # Number of nearest neighbors to find
dm <- dist(sites[,3:4])
nn <- matrix(0,n,k) # n x k nearest neighbors matrix
for (i in 1:n) {
   nn[i,] = k.nearest.neighbors(i, as.matrix(dm), k = k)
}
nn[] <- as.character(sites$siteclust)[c(nn)]

# Get names of all sites and their nearest neighbors
neighbors <- as_tibble(cbind(siteclust = as.character(sites$siteclust), nn))
# Get dhws of all sites and dhws of their nearest neighbors
neighborsdhw <- neighbors %>%
  pivot_longer(-1, names_to = "nno", values_to = "nname") %>%
  mutate(nno = parse_number(nno) - 1) %>%
  mutate(navgdhw = dhws$avgdhw[match(nname, dhws$siteclust)])

finddhw <- neighborsdhw %>%
  filter(siteclust %in% nodhw$siteclust)

dhwmatch <- finddhw %>% 
  group_by(siteclust) %>%
  filter(!is.na(navgdhw)) %>%
  dplyr::summarize(closest_n_with_dhw = nname[nno == min(nno)]) %>%
  right_join(nodhw) %>%
  dplyr::select(1, 2)# %>%
  #print(n = nrow(.))
  
# Output matches
matches <- left_join(dhwmatch, sites)
#range(matches$Longitude)
#range(matches$Latitude)
matches2 <- left_join(dplyr::select(matches, siteclust = closest_n_with_dhw), sites) %>%
  distinct(siteclust, lon, lat)
# 
# # Plot matches
# library(ggrepel)
# ggplot(matches, aes(x = lon, y = lat)) +
#   geom_point() +
#   geom_point(data = matches2, color = "green") +
#   geom_label_repel(data = matches2, aes(label = site), color = "green", max.overlaps = 100, force = 80) +
#   geom_label_repel(aes(label = site), max.overlaps = 100, force = 80) +
#   xlim(-80.125, -80) +
#   ylim(26, 26.75)

# Replace missing dhws with values from matching sites
#matches
fixing <- out %>%
  nest(data = c(date, dhw)) 

fixed <- fixing
### dhw data for sites where missing gets replaced with dhw data for the site of its closest neighbor site with dhw data
fixed[match(matches$siteclust, fixing$siteclust), "data"] <- fixing[match(matches$closest_n_with_dhw, fixing$siteclust), "data"]

# ### test if it worked (dhw was missing for site 100, should have been replaced with dhw data from KC)
# fixing %>% filter(site == "100") %>% pull(data)
# fixed %>% filter(site == "KC") %>% pull(data)
# 
# identical(fixed$data[fixed$site == "100"], fixed$data[fixed$site == "KC"])
# y1 <- fixed$data[fixed$site == "100"][[1]]
# y2 <- fixed$data[fixed$site == "KC"][[1]]
# cbind(y1, y2)

# Unnest fixed output
outfixed <- fixed %>% unnest()
#outfixed %>% filter(is.na(dhw))
dhws <- outfixed %>% dplyr::select(siteclust, lon, lat, date, dhw)

# We only downloaded DHW from June through December 2024, but we have Acro survey data from before and after that interval. Those surveys would have DHW values of zero, so add those in...
df11 <- expand_grid(
  date = seq(as.Date("2023-03-14"), as.Date("2024-05-10"), by = "days"),
  dhws %>% distinct(siteclust, lat, lon)
)
dhws <- full_join(dhws, df11) %>%
  arrange(siteclust, lon, lat, date) %>%
  replace_na(list(dhw = 0))


# Get max. DHW value for on OR BEFORE date surveyed
dhws <- dhws %>%
  group_by(siteclust) %>%
  mutate(cummaxdhw = cummax(dhw))


# For each survey, join DHW on date of survey, and max DHW experienced on or BEFORE date of survey
df <- left_join(df, dhws, by = c("siteclust", "lon", "lat", "date")) %>%
  mutate(subregion = factor(subregion, levels = levels(sites$subregion)))
```

```{r}
# Save integrated dataset to file
write_csv(df, file = "data/processed/FLAcro23_data_processed.csv")
```